import { QuestionType, Topic, Difficulty, type TrueFalseQuestion } from '@/types/question';

export const trueFalsePool: TrueFalseQuestion[] = [
  // ========== EXISTENCE & UNIQUENESS OF SOLUTIONS ==========
  {
    id: 'tf_exist_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If $f(x)$ is continuous, then the initial value problem $x\' = f(x)$, $x(0) = x_0$ always has a unique solution.',
    correctAnswer: false,
    explanation: 'Continuity guarantees existence (Peano theorem) but not uniqueness. For uniqueness, we need $f$ to be Lipschitz continuous. Example: $x\' = x^{2/3}$ has multiple solutions through $x(0) = 0$.',
  },
  {
    id: 'tf_exist_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If $f(x)$ is Lipschitz continuous, then the solution to $x\' = f(x)$, $x(0) = x_0$ exists for all $t \\in \\mathbb{R}$.',
    correctAnswer: false,
    explanation: 'Lipschitz continuity guarantees local existence and uniqueness (Picard-Lindelof), but solutions may blow up in finite time. Example: $x\' = x^2$ with $x(0) = 1$ blows up at $t = 1$.',
  },
  {
    id: 'tf_exist_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If $f$ and $\\frac{\\partial f}{\\partial x}$ are both bounded, then solutions to $x\' = f(x)$ exist for all time.',
    correctAnswer: true,
    explanation: 'Bounded $f$ implies bounded derivative of solutions, preventing finite-time blow-up. Bounded $\\partial f/\\partial x$ gives Lipschitz continuity, ensuring uniqueness.',
  },
  {
    id: 'tf_exist_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The function $x(t) = \\sin(t)$ can be a solution to some autonomous 1D system $x\' = f(x)$ with $x(0) = 0$.',
    correctAnswer: false,
    explanation: 'If $x(t) = \\sin(t)$ were a solution, then $x(0) = 0$ and $x(\\pi) = 0$. By uniqueness, both would give the same solution, but $x\'(0) = 1 \\neq -1 = x\'(\\pi)$. Contradiction.',
  },

  // ========== STABILITY & EQUILIBRIUM ==========
  {
    id: 'tf_stab_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A saddle point is always unstable.',
    correctAnswer: true,
    explanation: 'A saddle has eigenvalues with opposite signs, so trajectories escape along the unstable manifold. Since some nearby trajectories diverge, the equilibrium is unstable.',
  },
  {
    id: 'tf_stab_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If all eigenvalues of the Jacobian have negative real parts, the equilibrium is asymptotically stable.',
    correctAnswer: true,
    explanation: 'By the Hartman-Grobman theorem, a hyperbolic equilibrium with all eigenvalues having negative real parts is asymptotically stable.',
  },
  {
    id: 'tf_stab_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A center (pure imaginary eigenvalues) is asymptotically stable.',
    correctAnswer: false,
    explanation: 'A center has closed orbits around it. Trajectories neither approach nor escape the equilibrium, so it is stable (Lyapunov stable) but NOT asymptotically stable.',
  },
  {
    id: 'tf_stab_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A stable spiral (focus) has complex eigenvalues with negative real part.',
    correctAnswer: true,
    explanation: 'A spiral/focus occurs when eigenvalues are complex conjugates. The real part determines stability: negative real part means trajectories spiral inward (stable).',
  },
  {
    id: 'tf_stab_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For a 1D system $x\' = f(x)$, if $f\'(x^*) = 0$ at an equilibrium $x^*$, the equilibrium is always semistable.',
    correctAnswer: false,
    explanation: 'When $f\'(x^*) = 0$, the equilibrium is non-hyperbolic. It could be stable, unstable, or semistable depending on higher-order terms. More analysis is needed.',
  },
  {
    id: 'tf_stab_006',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For a 1D system $x\' = f(x)$, if $f\'(x^*) < 0$ at an equilibrium $x^*$, then $x^*$ is asymptotically stable.',
    correctAnswer: true,
    explanation: 'In 1D, $f\'(x^*) < 0$ means the flow pushes trajectories back toward $x^*$ from both sides, making it asymptotically stable.',
  },
  {
    id: 'tf_stab_007',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For a 2D linear system $\\mathbf{x}\' = A\\mathbf{x}$, the origin is stable if and only if $\\det(A) > 0$.',
    correctAnswer: false,
    explanation: 'Stability requires $\\text{tr}(A) < 0$ AND $\\det(A) > 0$. Having $\\det(A) > 0$ alone only ensures eigenvalues have the same sign (or are complex), but they could both be positive.',
  },
  {
    id: 'tf_stab_008',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A 2D linear system has a saddle if and only if $\\det(A) < 0$.',
    correctAnswer: true,
    explanation: 'The determinant equals the product of eigenvalues. $\\det(A) < 0$ means eigenvalues have opposite signs, which defines a saddle point.',
  },
  {
    id: 'tf_stab_009',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For $x\' = -x^5$, the origin is asymptotically stable.',
    correctAnswer: true,
    explanation: 'Although $f\'(0) = 0$ (non-hyperbolic), for $x > 0$ we have $f(x) < 0$ and for $x < 0$ we have $f(x) > 0$, so the flow always points toward the origin.',
  },
  {
    id: 'tf_stab_010',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For $x\' = x^3$, the origin is unstable.',
    correctAnswer: true,
    explanation: 'For $x > 0$, $f(x) > 0$ so solutions move away. For $x < 0$, $f(x) < 0$ so solutions also move away. The origin is unstable.',
  },
  {
    id: 'tf_stab_011',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For $x\' = x^2$, the origin is semistable.',
    correctAnswer: true,
    explanation: 'For $x > 0$, $f(x) > 0$ so solutions move away. For $x < 0$, $f(x) > 0$ so solutions approach origin. This is semistable (stable from one side only).',
  },

  // ========== BIFURCATIONS ==========
  {
    id: 'tf_bif_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_PITCHFORK,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A pitchfork bifurcation typically requires the system to have symmetry (e.g., $f(-x) = -f(x)$).',
    correctAnswer: true,
    explanation: 'The pitchfork bifurcation occurs when $f(0,\\mu) = 0$, $f_x(0,0) = 0$, $f_{xx}(0,0) = 0$, and $f_{xxx}(0,0) \\neq 0$. The condition $f_{xx} = 0$ typically arises from odd symmetry.',
  },
  {
    id: 'tf_bif_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_SADDLE_NODE,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'In a saddle-node bifurcation, two equilibria collide and annihilate each other.',
    correctAnswer: true,
    explanation: 'This is the defining characteristic: as the parameter crosses the bifurcation value, a stable and unstable equilibrium meet and disappear (or appear in reverse).',
  },
  {
    id: 'tf_bif_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_HOPF,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A Hopf bifurcation always produces a stable limit cycle.',
    correctAnswer: false,
    explanation: 'A supercritical Hopf produces a stable limit cycle (attracting), but a subcritical Hopf produces an unstable limit cycle (repelling).',
  },
  {
    id: 'tf_bif_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_TRANSCRITICAL,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'In a transcritical bifurcation, the number of equilibria changes.',
    correctAnswer: false,
    explanation: 'In a transcritical bifurcation, two equilibria exchange stability as they pass through each other. The total number of equilibria remains the same.',
  },
  {
    id: 'tf_bif_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_HOPF,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A Hopf bifurcation can only occur in systems of dimension $n \\geq 2$.',
    correctAnswer: true,
    explanation: 'Hopf bifurcation requires a pair of complex conjugate eigenvalues crossing the imaginary axis, which requires at least 2 dimensions.',
  },
  {
    id: 'tf_bif_006',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_PITCHFORK,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'In a supercritical pitchfork bifurcation, the new equilibria that appear are stable.',
    correctAnswer: true,
    explanation: 'In a supercritical pitchfork, as the parameter increases past the bifurcation, the origin loses stability and two new stable equilibria emerge.',
  },
  {
    id: 'tf_bif_007',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_PITCHFORK,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'In a subcritical pitchfork bifurcation, the new equilibria that appear are unstable.',
    correctAnswer: true,
    explanation: 'In a subcritical pitchfork, unstable equilibria exist before the bifurcation and collide with the origin, which then becomes unstable.',
  },
  {
    id: 'tf_bif_008',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_SADDLE_NODE,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The normal form for a saddle-node bifurcation is $x\' = r + x^2$.',
    correctAnswer: true,
    explanation: 'This is the standard normal form. For $r < 0$: two equilibria at $x = \\pm\\sqrt{-r}$. At $r = 0$: one equilibrium. For $r > 0$: no equilibria.',
  },
  {
    id: 'tf_bif_009',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_TRANSCRITICAL,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The normal form for a transcritical bifurcation is $x\' = rx - x^2$.',
    correctAnswer: true,
    explanation: 'This system always has equilibria at $x = 0$ and $x = r$. They exchange stability at $r = 0$.',
  },
  {
    id: 'tf_bif_010',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_HOPF,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'At a Hopf bifurcation, the equilibrium always changes stability.',
    correctAnswer: true,
    explanation: 'At a Hopf bifurcation, a pair of complex eigenvalues crosses the imaginary axis, changing from negative to positive real part (or vice versa), thus changing stability.',
  },
  {
    id: 'tf_bif_011',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_HOPF,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'In a supercritical Hopf bifurcation, the limit cycle exists for parameter values where the equilibrium is unstable.',
    correctAnswer: true,
    explanation: 'In supercritical Hopf, the stable limit cycle appears as the equilibrium loses stability, coexisting with the now-unstable equilibrium.',
  },

  // ========== CENTER MANIFOLD ==========
  {
    id: 'tf_cm_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.CENTER_MANIFOLD,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The center manifold is always unique.',
    correctAnswer: false,
    explanation: 'The center manifold is generally NOT unique globally. However, its Taylor expansion at the equilibrium point is unique to any finite order.',
  },
  {
    id: 'tf_cm_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.CENTER_MANIFOLD,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The center manifold theorem allows us to reduce the study of stability to a lower-dimensional system.',
    correctAnswer: true,
    explanation: 'The center manifold theorem states that the stability of a non-hyperbolic equilibrium is determined by the dynamics on the center manifold, which has dimension equal to the number of zero/purely imaginary eigenvalues.',
  },
  {
    id: 'tf_cm_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.CENTER_MANIFOLD,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The center manifold is tangent to the center eigenspace at the equilibrium.',
    correctAnswer: true,
    explanation: 'By the center manifold theorem, the center manifold $W^c$ is tangent to the eigenspace $E^c$ corresponding to eigenvalues with zero real part.',
  },
  {
    id: 'tf_cm_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.CENTER_MANIFOLD,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If a system has a zero eigenvalue at the origin, we must use center manifold theory to determine stability.',
    correctAnswer: true,
    explanation: 'A zero eigenvalue makes the equilibrium non-hyperbolic, so linearization cannot determine stability. Center manifold reduction is needed.',
  },
  {
    id: 'tf_cm_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.CENTER_MANIFOLD,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The center manifold $W^c$ is invariant under the flow.',
    correctAnswer: true,
    explanation: 'By definition, the center manifold is an invariant manifold tangent to the center eigenspace. Trajectories starting on $W^c$ stay on $W^c$.',
  },

  // ========== INVARIANT MANIFOLDS ==========
  {
    id: 'tf_man_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The stable manifold of a hyperbolic fixed point has dimension equal to the number of eigenvalues with negative real parts.',
    correctAnswer: true,
    explanation: 'By the stable manifold theorem, $\\dim(W^s) = $ number of eigenvalues with $\\text{Re}(\\lambda) < 0$.',
  },
  {
    id: 'tf_man_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Trajectories on the stable manifold approach the equilibrium as $t \\to +\\infty$.',
    correctAnswer: true,
    explanation: 'By definition, the stable manifold $W^s$ consists of all points whose forward orbit converges to the equilibrium.',
  },
  {
    id: 'tf_man_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The stable and unstable manifolds of a saddle point can intersect.',
    correctAnswer: true,
    explanation: 'They intersect at the saddle point itself. In higher dimensions or for homoclinic/heteroclinic orbits, there can be additional intersections.',
  },
  {
    id: 'tf_man_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The stable manifold $W^s$ is tangent to the stable eigenspace $E^s$ at the equilibrium.',
    correctAnswer: true,
    explanation: 'By the stable manifold theorem, near the equilibrium, $W^s$ is tangent to the eigenspace corresponding to eigenvalues with negative real part.',
  },
  {
    id: 'tf_man_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A homoclinic orbit connects a saddle point to itself.',
    correctAnswer: true,
    explanation: 'A homoclinic orbit is a trajectory that lies in both the stable and unstable manifolds of the same equilibrium, approaching it as $t \\to \\pm\\infty$.',
  },
  {
    id: 'tf_man_006',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A heteroclinic orbit connects two different equilibrium points.',
    correctAnswer: true,
    explanation: 'A heteroclinic orbit approaches one equilibrium as $t \\to -\\infty$ and a different equilibrium as $t \\to +\\infty$.',
  },

  // ========== TOPOLOGICAL INDEX ==========
  {
    id: 'tf_idx_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.TOPOLOGICAL_INDEX,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The index of a saddle point is $-1$.',
    correctAnswer: true,
    explanation: 'The index of a hyperbolic equilibrium is $(-1)^k$ where $k$ is the number of eigenvalues with positive real part. For a saddle, $k=1$, so index $= -1$.',
  },
  {
    id: 'tf_idx_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.TOPOLOGICAL_INDEX,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The index of a node (stable or unstable) is $+1$.',
    correctAnswer: true,
    explanation: 'A stable node has $k=0$ eigenvalues with positive real part: index $= (-1)^0 = 1$. An unstable node has $k=2$: index $= (-1)^2 = 1$.',
  },
  {
    id: 'tf_idx_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.TOPOLOGICAL_INDEX,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The index of a spiral (focus) is $+1$.',
    correctAnswer: true,
    explanation: 'A spiral has complex eigenvalues with nonzero real part. Stable spiral: $k=0$, unstable spiral: $k=2$. Both give index $= 1$.',
  },
  {
    id: 'tf_idx_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.TOPOLOGICAL_INDEX,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A limit cycle must contain at least one equilibrium point in its interior.',
    correctAnswer: true,
    explanation: 'By the Poincare index theorem, a limit cycle has index +1, and the sum of indices of equilibria inside must equal +1. Since all equilibria have nonzero index, there must be at least one.',
  },
  {
    id: 'tf_idx_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.TOPOLOGICAL_INDEX,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If a region contains only one equilibrium (a saddle), there cannot be a limit cycle surrounding it.',
    correctAnswer: true,
    explanation: 'A limit cycle requires index +1 inside. A saddle has index -1, so a limit cycle cannot enclose only a saddle.',
  },
  {
    id: 'tf_idx_006',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.TOPOLOGICAL_INDEX,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The index of a center is $+1$.',
    correctAnswer: true,
    explanation: 'A center has purely imaginary eigenvalues. Using the formula $(-1)^k$ with $k$ being eigenvalues with positive real part gives $(-1)^0 = 1$ (since real parts are zero, not positive).',
  },

  // ========== LYAPUNOV FUNCTIONS ==========
  {
    id: 'tf_lyap_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LYAPUNOV_FUNCTIONS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If $V(x)$ is a Lyapunov function with $\\dot{V} < 0$ for all $x \\neq 0$, then the origin is asymptotically stable.',
    correctAnswer: true,
    explanation: 'This is Lyapunov\'s direct method: $V > 0$, $V(0) = 0$, and $\\dot{V} < 0$ for $x \\neq 0$ implies asymptotic stability.',
  },
  {
    id: 'tf_lyap_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LYAPUNOV_FUNCTIONS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If $\\dot{V} \\leq 0$ (but not strictly negative), we can only conclude stability, not asymptotic stability.',
    correctAnswer: true,
    explanation: 'With $\\dot{V} \\leq 0$, trajectories don\'t increase $V$, ensuring stability. But without strict decrease, trajectories might not converge to the origin. LaSalle\'s invariance principle can sometimes help.',
  },
  {
    id: 'tf_lyap_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LYAPUNOV_FUNCTIONS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Every asymptotically stable equilibrium has a Lyapunov function.',
    correctAnswer: true,
    explanation: 'This is the converse Lyapunov theorem: asymptotic stability implies the existence of a smooth Lyapunov function (though finding it explicitly may be difficult).',
  },
  {
    id: 'tf_lyap_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LYAPUNOV_FUNCTIONS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: '$V(x,y) = x^2 + y^2$ is positive definite.',
    correctAnswer: true,
    explanation: '$V(0,0) = 0$ and $V(x,y) > 0$ for all $(x,y) \\neq (0,0)$. This is the definition of positive definite.',
  },
  {
    id: 'tf_lyap_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LYAPUNOV_FUNCTIONS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A Lyapunov function can be used to prove instability.',
    correctAnswer: true,
    explanation: 'Chetaev\'s theorem: if $V$ is positive in some region touching the origin and $\\dot{V} > 0$ in that region, the origin is unstable.',
  },

  // ========== HAMILTONIAN SYSTEMS ==========
  {
    id: 'tf_ham_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.HAMILTONIAN_SYSTEMS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Hamiltonian systems cannot have asymptotically stable equilibria.',
    correctAnswer: true,
    explanation: 'Hamiltonian systems preserve volume (Liouville\'s theorem) and conserve the Hamiltonian $H$. Asymptotic stability requires volume contraction, which is impossible.',
  },
  {
    id: 'tf_ham_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.HAMILTONIAN_SYSTEMS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For a Hamiltonian system, the Hamiltonian $H$ is constant along trajectories.',
    correctAnswer: true,
    explanation: '$\\frac{dH}{dt} = \\frac{\\partial H}{\\partial q}\\dot{q} + \\frac{\\partial H}{\\partial p}\\dot{p} = \\frac{\\partial H}{\\partial q}\\frac{\\partial H}{\\partial p} - \\frac{\\partial H}{\\partial p}\\frac{\\partial H}{\\partial q} = 0$',
  },
  {
    id: 'tf_ham_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.HAMILTONIAN_SYSTEMS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A 2D Hamiltonian system has $\\text{div}(\\mathbf{f}) = 0$ (divergence-free).',
    correctAnswer: true,
    explanation: 'For $\\dot{x} = \\partial H/\\partial y$, $\\dot{y} = -\\partial H/\\partial x$: $\\text{div} = \\partial^2 H/\\partial x \\partial y - \\partial^2 H/\\partial y \\partial x = 0$.',
  },
  {
    id: 'tf_ham_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.HAMILTONIAN_SYSTEMS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Trajectories of a Hamiltonian system are level curves of $H$.',
    correctAnswer: true,
    explanation: 'Since $H$ is constant along trajectories, each trajectory lies on a level set $H(x,y) = c$ for some constant $c$.',
  },
  {
    id: 'tf_ham_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.HAMILTONIAN_SYSTEMS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Hamiltonian systems cannot have limit cycles.',
    correctAnswer: true,
    explanation: 'A limit cycle would require trajectories to spiral in/out, but Hamiltonian systems conserve $H$, so trajectories are level curves that cannot spiral.',
  },

  // ========== PHASE PORTRAITS ==========
  {
    id: 'tf_phase_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'In a 2D autonomous system, two distinct trajectories can intersect.',
    correctAnswer: false,
    explanation: 'By uniqueness of solutions, if two trajectories passed through the same point, they would be the same trajectory. Distinct trajectories cannot intersect (except at equilibria).',
  },
  {
    id: 'tf_phase_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The Poincare-Bendixson theorem implies that a bounded trajectory in 2D must approach either an equilibrium or a limit cycle.',
    correctAnswer: true,
    explanation: 'For 2D autonomous systems, a trajectory that stays in a bounded region with finitely many equilibria must have its $\\omega$-limit set be an equilibrium, a limit cycle, or a graph of equilibria and connecting orbits.',
  },
  {
    id: 'tf_phase_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Chaos is possible in 2D autonomous continuous-time systems.',
    correctAnswer: false,
    explanation: 'The Poincare-Bendixson theorem rules out chaos in 2D. Chaos requires at least 3 dimensions for continuous-time autonomous systems.',
  },
  {
    id: 'tf_phase_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If $\\text{div}(\\mathbf{f}) \\neq 0$ everywhere in a region, there are no limit cycles in that region.',
    correctAnswer: true,
    explanation: 'This is the Bendixson-Dulac criterion. If divergence has constant sign (and is nonzero), limit cycles cannot exist.',
  },
  {
    id: 'tf_phase_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Nullclines are curves where either $\\dot{x} = 0$ or $\\dot{y} = 0$.',
    correctAnswer: true,
    explanation: 'The $x$-nullcline is where $\\dot{x} = 0$ (flow is vertical), and the $y$-nullcline is where $\\dot{y} = 0$ (flow is horizontal). Equilibria occur at intersections.',
  },
  {
    id: 'tf_phase_006',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Equilibrium points occur at intersections of nullclines.',
    correctAnswer: true,
    explanation: 'At an equilibrium, both $\\dot{x} = 0$ and $\\dot{y} = 0$, so the point lies on both nullclines.',
  },

  // ========== MORE ADVANCED CONCEPTUAL ==========
  {
    id: 'tf_adv_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Linear coordinate changes preserve the stability type of an equilibrium.',
    correctAnswer: true,
    explanation: 'A linear change of coordinates $y = Px$ (with $P$ invertible) transforms $\\dot{x} = Ax$ to $\\dot{y} = PAP^{-1}y$. The eigenvalues of $PAP^{-1}$ are the same as those of $A$.',
  },
  {
    id: 'tf_adv_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The Hartman-Grobman theorem states that near a hyperbolic equilibrium, the nonlinear system is topologically equivalent to its linearization.',
    correctAnswer: true,
    explanation: 'This theorem guarantees that the phase portrait near a hyperbolic equilibrium looks qualitatively like that of the linearized system.',
  },
  {
    id: 'tf_adv_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'An equilibrium is hyperbolic if all eigenvalues of the Jacobian have nonzero real parts.',
    correctAnswer: true,
    explanation: 'By definition, a hyperbolic equilibrium has no eigenvalues on the imaginary axis (no zero or purely imaginary eigenvalues).',
  },
  {
    id: 'tf_adv_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For a 2D linear system, $\\text{tr}(A) = \\lambda_1 + \\lambda_2$ and $\\det(A) = \\lambda_1 \\lambda_2$.',
    correctAnswer: true,
    explanation: 'These are fundamental properties relating the matrix entries to eigenvalues. They form the basis for the trace-determinant classification.',
  },
  {
    id: 'tf_adv_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The discriminant $\\Delta = \\text{tr}^2(A) - 4\\det(A)$ determines whether eigenvalues are real or complex.',
    correctAnswer: true,
    explanation: '$\\Delta > 0$: real distinct eigenvalues. $\\Delta = 0$: repeated real eigenvalue. $\\Delta < 0$: complex conjugate eigenvalues.',
  },
  {
    id: 'tf_adv_006',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A trapping region guarantees the existence of either an equilibrium or a limit cycle inside.',
    correctAnswer: true,
    explanation: 'By Poincare-Bendixson, if trajectories enter a bounded region and cannot escape, the $\\omega$-limit set must contain an equilibrium or limit cycle.',
  },
  {
    id: 'tf_adv_007',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'In 1D, a flow $\\phi_t(x)$ satisfies $\\phi_{s+t}(x) = \\phi_s(\\phi_t(x))$.',
    correctAnswer: true,
    explanation: 'This is the group property of flows. Flowing for time $t$ then time $s$ is the same as flowing for time $s+t$.',
  },
  {
    id: 'tf_adv_008',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The function $\\phi_t(x) = e^t x$ is a flow for the system $x\' = x$.',
    correctAnswer: true,
    explanation: 'Check: $\\frac{d}{dt}\\phi_t(x) = e^t x = \\phi_t(x)$, which matches $x\' = x$. Also $\\phi_0(x) = x$ as required.',
  },

  // ========== EXAM-STYLE FLOW QUESTIONS ==========
  {
    id: 'tf_flow_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The function $\\phi_t(x) = x + t$ is a flow for some 1D autonomous system.',
    correctAnswer: true,
    explanation: 'Yes, this is the flow of $x\' = 1$. Check: $\\phi_0(x) = x$ and $\\frac{d}{dt}\\phi_t(x) = 1$.',
  },
  {
    id: 'tf_flow_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The function $\\phi_t(x) = tx$ is a flow for some 1D autonomous system.',
    correctAnswer: false,
    explanation: 'No. A flow must satisfy $\\phi_0(x) = x$, but $\\phi_0(x) = 0 \\cdot x = 0 \\neq x$ for $x \\neq 0$.',
  },
  {
    id: 'tf_flow_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The function $\\phi_t(x) = e^{xt}$ is a flow for some 1D autonomous system.',
    correctAnswer: false,
    explanation: 'Check $\\phi_0(x) = e^0 = 1 \\neq x$ for general $x$. This fails the initial condition for a flow.',
  },

  // ========== COORDINATE TRANSFORMATION QUESTIONS ==========
  {
    id: 'tf_coord_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A change to polar coordinates $(r, \\theta)$ is a linear coordinate transformation.',
    correctAnswer: false,
    explanation: 'No. The transformation $x = r\\cos\\theta$, $y = r\\sin\\theta$ is nonlinear in $(r, \\theta)$.',
  },
  {
    id: 'tf_coord_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The stability of a stationary point can be changed by a nonlinear coordinate transformation.',
    correctAnswer: false,
    explanation: 'No. Stability is a topological property preserved under diffeomorphisms (smooth invertible maps with smooth inverse).',
  },
  {
    id: 'tf_coord_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.LINEAR_SYSTEMS_2D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The linear system $\\dot{x} = -y$, $\\dot{y} = x$ becomes decoupled in polar coordinates.',
    correctAnswer: true,
    explanation: 'In polar: $\\dot{r} = 0$, $\\dot{\\theta} = 1$. The equations are separated (decoupled) with constant $r$ and linear $\\theta$.',
  },

  // ========== LIMIT CYCLE AND POINCARÉ-BENDIXSON ==========
  {
    id: 'tf_lc_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A stable limit cycle attracts all nearby trajectories from both inside and outside.',
    correctAnswer: true,
    explanation: 'By definition, a stable (attracting) limit cycle has trajectories spiraling toward it from both the interior and exterior.',
  },
  {
    id: 'tf_lc_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If a 2D system has exactly one equilibrium (an unstable focus) in a trapping region, a limit cycle must exist.',
    correctAnswer: true,
    explanation: 'By Poincaré-Bendixson, trajectories must approach either an equilibrium or limit cycle. Since the only equilibrium is unstable, trajectories must approach a limit cycle.',
  },
  {
    id: 'tf_lc_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A limit cycle can enclose exactly two equilibria: one stable focus and one saddle.',
    correctAnswer: false,
    explanation: 'The index of a stable focus is +1 and saddle is -1. Total index = +1 + (-1) = 0, but a limit cycle requires total index +1 inside. So this configuration cannot support a limit cycle.',
  },
  {
    id: 'tf_lc_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.PHASE_PORTRAITS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'A limit cycle must have index $+1$.',
    correctAnswer: true,
    explanation: 'The index of a simple closed curve (like a limit cycle) equals the sum of indices of equilibria inside. A limit cycle has index +1.',
  },

  // ========== HIGHER-ORDER STABILITY ==========
  {
    id: 'tf_ho_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For $x\' = -x^5$, linearization at the origin gives $f\'(0) = 0$, so stability cannot be determined by linearization.',
    correctAnswer: true,
    explanation: 'The derivative $f\'(x) = -5x^4$ vanishes at $x=0$, making the origin non-hyperbolic. Higher-order analysis shows it\'s stable.',
  },
  {
    id: 'tf_ho_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For $x\' = x^4$, the origin is semistable.',
    correctAnswer: false,
    explanation: 'For $x \\neq 0$, $x^4 > 0$ always. So trajectories move right for both $x > 0$ and $x < 0$. The origin is unstable (not semistable).',
  },
  {
    id: 'tf_ho_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For $x\' = -x^4$, the origin is asymptotically stable.',
    correctAnswer: false,
    explanation: 'For $x > 0$: $-x^4 < 0$, trajectories move left (toward origin). For $x < 0$: $-x^4 < 0$, trajectories also move left (away from origin). This is semistable.',
  },
  {
    id: 'tf_ho_004',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For $x\' = \\sin(x) - x$, the origin is asymptotically stable.',
    correctAnswer: true,
    explanation: '$f(x) = \\sin(x) - x$. Taylor: $\\sin(x) = x - x^3/6 + ...$, so $f(x) \\approx -x^3/6$. Since leading nonlinear term is $-x^3$, origin is asymptotically stable.',
  },

  // ========== NORMAL FORMS ==========
  {
    id: 'tf_nf_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.CENTER_MANIFOLD,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Near-identity coordinate transformations are used to simplify nonlinear terms in normal form theory.',
    correctAnswer: true,
    explanation: 'Normal form theory uses near-identity transformations $x = y + h(y)$ where $h$ contains only nonlinear terms, to eliminate or simplify nonlinear terms.',
  },
  {
    id: 'tf_nf_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.CENTER_MANIFOLD,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'All nonlinear terms can be eliminated by coordinate transformations near a non-hyperbolic equilibrium.',
    correctAnswer: false,
    explanation: 'Some nonlinear terms are "resonant" and cannot be eliminated. These determine the qualitative behavior (bifurcations, stability).',
  },

  // ========== TOPOLOGICAL EQUIVALENCE ==========
  {
    id: 'tf_topo_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The systems $x\' = x$ and $x\' = 2x$ are topologically equivalent.',
    correctAnswer: true,
    explanation: 'Both have the same qualitative behavior: origin is unstable, trajectories escape to infinity. A time reparametrization relates them.',
  },
  {
    id: 'tf_topo_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The systems $x\' = x$ and $x\' = x^2$ are topologically equivalent.',
    correctAnswer: false,
    explanation: '$x\' = x$ has one equilibrium at origin. $x\' = x^2$ also has one at origin, but the behavior differs: for $x\' = x^2$, all trajectories move right.',
  },
  {
    id: 'tf_topo_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.EQUILIBRIUM_CLASSIFICATION,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'Two 1D systems with different numbers of equilibria cannot be topologically equivalent.',
    correctAnswer: true,
    explanation: 'Topological equivalence preserves the number and type of equilibria. Different counts mean different topology.',
  },

  // ========== SPECIFIC BIFURCATION SCENARIOS ==========
  {
    id: 'tf_bif_012',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_HOPF,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'At a Hopf bifurcation, the eigenvalues of the Jacobian are purely imaginary.',
    correctAnswer: true,
    explanation: 'At the Hopf bifurcation point, eigenvalues are $\\pm i\\omega$ for some $\\omega > 0$. They cross the imaginary axis as the parameter varies.',
  },
  {
    id: 'tf_bif_013',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_HOPF,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The transversality condition for Hopf bifurcation requires $\\frac{d}{d\\mu}\\text{Re}(\\lambda)|_{\\mu=\\mu_0} \\neq 0$.',
    correctAnswer: true,
    explanation: 'Transversality ensures eigenvalues cross the imaginary axis with nonzero speed, guaranteeing a genuine bifurcation.',
  },
  {
    id: 'tf_bif_014',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.BIFURCATION_SADDLE_NODE,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'At a saddle-node bifurcation, exactly one eigenvalue of the Jacobian is zero.',
    correctAnswer: true,
    explanation: 'A saddle-node bifurcation in 1D (or the center manifold reduction) has $f_x(x^*, \\mu^*) = 0$, corresponding to a zero eigenvalue.',
  },

  // ========== INVARIANT SETS ==========
  {
    id: 'tf_inv_001',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For the system $\\dot{x} = 3x$, $\\dot{y} = -2y + x^2$, the $x$-axis is an invariant set.',
    correctAnswer: false,
    explanation: 'On the $x$-axis, $y = 0$, so $\\dot{y} = -2(0) + x^2 = x^2 \\neq 0$ for $x \\neq 0$. Trajectories starting on the $x$-axis immediately leave it, so it is NOT invariant.',
  },
  {
    id: 'tf_inv_002',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'For the system $\\dot{x} = 3x$, $\\dot{y} = -2y + x^2$, the $y$-axis is an invariant set.',
    correctAnswer: true,
    explanation: 'On the $y$-axis, $x = 0$, so $\\dot{x} = 3(0) = 0$. Trajectories starting with $x=0$ stay at $x=0$. The $y$-axis is invariant.',
  },
  {
    id: 'tf_inv_003',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.INVARIANT_MANIFOLDS,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'An invariant manifold contains entire trajectories (both forward and backward in time).',
    correctAnswer: true,
    explanation: 'By definition, if a trajectory starts on an invariant manifold, it stays on the manifold for all time (positive and negative).',
  },

  // ========== EXISTENCE THEORY ==========
  {
    id: 'tf_exist_005',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'If $|f(x)| \\leq M$ for all $x$, then solutions to $x\' = f(x)$ exist for all $t \\in \\mathbb{R}$.',
    correctAnswer: true,
    explanation: 'Bounded $f$ implies $|x(t) - x_0| \\leq M|t|$, so solutions cannot blow up in finite time.',
  },
  {
    id: 'tf_exist_006',
    type: QuestionType.TRUE_FALSE,
    topic: Topic.STABILITY_1D,
    difficulty: Difficulty.CONCEPTUAL,
    prompt: 'The solution $x(t)$ to $x\' = f(x)$ is constant if and only if $f(x(0)) = 0$.',
    correctAnswer: true,
    explanation: 'Constant solutions are equilibria. $x(t) = c$ implies $0 = x\'(t) = f(c)$, so $f(x(0)) = f(c) = 0$.',
  },
];
